name: build_publish_release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies for Ubuntu
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install app dependencies
        run: npm install

      - name: Build the app Windows
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add i686-pc-windows-msvc
          rustup target add x86_64-pc-windows-msvc
          npm run tauri build -- --target i686-pc-windows-msvc
          npm run tauri build -- --target x86_64-pc-windows-msvc

      - name: Upload Artifact Windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_x64
          path: |
            src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/
          if-no-files-found: warn

  publish_release:
    needs: [build_release]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        # si aucun name, il récupére tout les artefacts uploader précédemment par défault.

      - name: List Files
        run: |
          ls windows-x86_x64

      - name: Add assets and publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          name: 'Crzgames Launcher v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          body: 'Distribution for Windows / MacOS / Linux'
          draft: false
          prerelease: false
          files: |
            windows-x86_x64/i686-pc-windows-msvc/release/bundle/msi/*
            windows-x86_x64/x86_64-pc-windows-msvc/release/bundle/msi/*