name: build_release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install app dependencies and build web
        run: npm install

      - name: Build the app Windows
        run: rustup target add i686-pc-windows-msvc && rustup target add x86_64-pc-windows-msvc && npm run tauri build -- --target i686-pc-windows-msvc

      - name: Upload Artifact Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_x64
          path: src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Add assets to Release for Windows
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          name: 'Crzgames Launcher v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          body: 'Distribution for Windows / MacOS / Linux'
          draft: false
          prerelease: false
          files: src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/